MVCBoletas/Controllers/GrupoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BL;

namespace TuProyecto.Controllers
{
    public class GrupoController : Controller
    {
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Grupo grupo = new ML.Grupo(); // instancia para las propiedades
            ML.Result result = BL.Grupo.GetAll();

            if (result.Correct)
            {
                grupo.Grupos = result.Objects;
                return View(grupo);
            }
            return View(grupo);
        }
        public ActionResult Form(int? IdGrupo)
        {
            ML.Grupo grupo = new ML.Grupo();

            if (IdGrupo.HasValue)
            {
                var result = BL.Grupo.GetById(IdGrupo.Value);

                if (result.Correct)
                {
                    grupo = result.Objects.FirstOrDefault() as ML.Grupo ?? new ML.Grupo();
                }
                else
                {
                    // Manejo de error o redirección en caso de fallo
                    ViewBag.ErrorMessage = result.ErrorMessage; // Puedes utilizar ViewBag para mostrar mensajes de error en la vista
                    return View("Error"); // Reemplaza "Error" con el nombre de tu vista de error
                }
            }

            return View(grupo);
        }

        [HttpPost]
        public ActionResult Form(ML.Grupo grupo)
        {
            try
            {
                if (grupo.IdGrupo == 0)
                {
                    var result = BL.Grupo.Add(grupo);

                    if (result.Correct)
                    {
                        ViewBag.Mensaje = "Registro exitoso";
                        return PartialView("Modal");
                    }
                    else
                    {
                        ViewBag.Mensaje = "Ocurrió un problema al agregar el registro: " + result.ErrorMessage;
                        return PartialView("Modal");
                    }
                }
                else
                {
                    var result = BL.Grupo.Update(grupo);

                    if (result.Correct)
                    {
                        ViewBag.Mensaje = "Actualización exitosa";
                        return PartialView("Modal");
                    }
                    else
                    {
                        ViewBag.Mensaje = "Ocurrió un problema al actualizar el registro: " + result.ErrorMessage;
                        return PartialView("Modal");
                    }
                }
            }
            catch (Exception ex)
            {
                // Loguea o maneja el error según tus necesidades
                ViewBag.Mensaje = "Ocurrió un problema: " + ex.Message;
                return PartialView("Modal");
            }
        }
        [HttpPost]
        public ActionResult Delete(int IdGrupo)
        {
            try
            {
                var result = BL.Grupo.Delete(IdGrupo);

                if (result.Correct)
                {
                    ViewBag.Mensaje = "Eliminación exitosa";
                    return PartialView("Modal");
                }
                else
                {
                    ViewBag.Mensaje = "Ocurrió un problema al eliminar el registro: " + result.ErrorMessage;
                    return PartialView("Modal");
                }
            }
            catch (Exception ex)
            {
                // Loguea o maneja el error según tus necesidades
                ViewBag.Mensaje = "Ocurrió un problema: " + ex.Message;
                return PartialView("Modal");
            }
        }
    }
}

MVCBoletas/Views/Grupo/Form.cshtml
@model ML.Grupo

<div>
    <h2>Formulario de Grupo</h2>

    @using (Html.BeginForm("Form", "Grupo", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.LabelFor(model => model.Nombregrupo, "Nombre del Grupo")
            @Html.EditorFor(model => model.Nombregrupo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombregrupo, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdMateria, "ID de Materia")
            @Html.EditorFor(model => model.IdMateria, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IdMateria, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdProfesor, "ID de Profesor")
            @Html.EditorFor(model => model.IdProfesor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IdProfesor, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <input type="submit" value="Guardar" class="btn btn-primary" />
        </div>
    }
</div>

MVCBoletas/Views/Grupo/GetAll.cshtml
@model ML.Grupo
@{
    ViewBag.Title = "GetAll";
}

<h2>Grupos</h2>

<div class="row">
    <div class="col-md-12">
        <h5>Seleccione un Grupo para editarlo o + para agregar...</h5>
    </div>
</div>

<div style="float:right;">
    @Html.ActionLink("+", "Form", "Grupo", htmlAttributes: new { @class = "btn btn-success" })
</div>
<br />

<table class="table table-bordered table-responsive">
    <thead>
        <tr>
            <td>Editar</td>

            <td class="visually-hidden">IdGrupo</td>
            <td>Nombre del Grupo</td>
            <td class="visually-hidden">IdMateria</td>
            <td>Nombre de la Materia</td>
            <td class="visually-hidden">IdProfesor</td>
            <td>Nombre del Profesor</td>

            <td>Eliminar</td>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Grupos != null)
        {
            foreach (ML.Grupo grupo in Model.Grupos)
            {
                <tr>
                    <td><a class="btn btn-warning" href="@Url.Action("Form", "Grupo", new {IdGrupo = grupo.IdGrupo})"><i class="fas fa-pencil-alt"></i></a></td>
                    <td class="visually-hidden">@grupo.IdGrupo</td>
                    <td>@grupo.Nombregrupo</td>

                    <td class="visually-hidden">@grupo.IdMateria</td>
                    <td>@grupo.NombreMateria</td>

                    <td class="visually-hidden">@grupo.IdProfesor</td>
                    <td>@grupo.NombreProfesor</td>

                    <td><a class="btn btn-danger" href="@Url.Action("Delete", "Grupo", new {IdGrupo = grupo.IdGrupo })" onclick="return confirm('Estás seguro que deseas eliminar este registro?');"><i class="fas fa-trash"></i></a></td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="7">No hay datos disponibles</td>
            </tr>
        }
    </tbody>

</table>

MVCBoletas/Views/Grupo/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAll", "Grupo", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#modalValidacion').modal('show');
    });
</script>