MVCBoletas/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
     // Asegúrate de reemplazar "YourNamespace" con el namespace correcto

namespace YourNamespace.Controllers
{
    public class AlumnoController : Controller
    {
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Alumno alumno = new ML.Alumno();
            var result = BL.Alumno.GetAll();

            if (result.Correct)
            {
                alumno.Alumnos = result.Objects;
            }

            return View(alumno);
        }

        [HttpGet]
        public ActionResult Form(int? IdAlumno)
        {
            ML.Alumno alumno = new ML.Alumno();

            if (IdAlumno != null)
            {
                var result = BL.Alumno.GetById(IdAlumno.Value);
                if (result.Correct)
                {
                    alumno = (ML.Alumno)result.Object;
                }
            }

            return View(alumno);
        }

        [HttpPost]
        public ActionResult Form(ML.Alumno alumno)
        {
            try
            {
                if (alumno.IdAlumno == 0)
                {
                    var result = BL.Alumno.Add(alumno);

                    if (result.Correct)
                    {
                        ViewBag.Mensaje = "Registro exitoso";
                        return PartialView("Modal");
                    }
                    else
                    {
                        ViewBag.Mensaje = "Ocurrió un problema al agregar el registro: " + result.ErrorMessage;
                        return PartialView("Modal");
                    }
                }
                else
                {
                    var result = BL.Alumno.Update(alumno);

                    if (result.Correct)
                    {
                        ViewBag.Mensaje = "Actualización exitosa";
                        return PartialView("Modal");
                    }
                    else
                    {
                        ViewBag.Mensaje = "Ocurrió un problema al actualizar el registro: " + result.ErrorMessage;
                        return PartialView("Modal");
                    }
                }
            }
            catch (Exception ex)
            {
                // Loguea o maneja el error según tus necesidades
                ViewBag.Mensaje = "Ocurrió un problema: " + ex.Message;
                return PartialView("Modal");
            }
        }

        [HttpGet]
        public ActionResult Delete(int? IdAlumno)
        {
            

            var result = BL.Alumno.Delete(IdAlumno.Value);

            if (result.Correct)
            {
                ViewBag.Mensaje = "Registro eliminado exitosamente";
                return PartialView("Modal");
            }
            else
            {
                ViewBag.Mensaje = "Ocurrió un problema al eliminar el registro: " + result.ErrorMessage;
                return PartialView("Modal");
            }
        }

    }
}

MVCBoletas/Views/Alumno/Form.cshtml
@model ML.Alumno

@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Formulario para agregar un nuevo Alumno</h2>
<div class="row">
    <div class="container">
        <div class="col-md-12">
            <h2>Alumnos</h2>
            <h5>Ingrese los datos del Alumno:</h5>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @* Crea un salto de línea *@
            <hr />
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Alumno", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-group">
                    @Html.HiddenFor(model => model.IdAlumno)
                </div>

                <div class="form-group col-md-4 col-12 col-sm-6">
                    @Html.LabelFor(model => model.Nombre)
                    @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre" })
                    @Html.ValidationMessageFor(model => model.Nombre)
                </div>

                <div class="form-group col-md-4 col-12 col-sm-6">
                    @Html.LabelFor(model => model.NombreBoleta)
                    @Html.TextBoxFor(model => model.NombreBoleta, new { @class = "form-control", @id = "txtNombreBoleta" })
                    @Html.ValidationMessageFor(model => model.NombreBoleta)
                </div>

                <div class="form-group col-md-4 col-12 col-sm-6">
                    @Html.LabelFor(model => model.UserName)
                    @Html.TextBoxFor(model => model.UserName, new { @class = "form-control", @id = "txtUserName" })
                    @Html.ValidationMessageFor(model => model.UserName)
                </div>

                <div class="form-group col-md-4 col-12 col-sm-6">
                    @Html.LabelFor(model => model.Password)
                    @Html.TextBoxFor(model => model.Password, new { @class = "form-control", @id = "txtPassword" })
                    @Html.ValidationMessageFor(model => model.Password)
                </div>

                <div class="form-group col-md-4 col-12 col-sm-6">
                    @Html.LabelFor(model => model.Email)
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @id = "txtEmail" })
                    @Html.ValidationMessageFor(model => model.Email)
                </div>

                <div class="form-group col-md-4 col-12 col-sm-6">
                    @Html.LabelFor(model => model.Telefono)
                    @Html.TextBoxFor(model => model.Telefono, new { @class = "form-control", @id = "txtTelefono" })
                    @Html.ValidationMessageFor(model => model.Telefono)
                </div>

                <div class="col">
                    <div class="col-md-3">
                        <input type="submit" value="Guardar" class="btn btn-success" />
                        @Html.ActionLink("Regresar", "GetAll", "Biblioteca", htmlAttributes: new { @class = "btn btn-danger" })
                    </div>
                </div>
            }
        </div>
    </div>
</div>

MVCBoletas/Views/Alumno/GetAll.cshtml
@model ML.Alumno
@{
    ViewBag.Title = "GetAll";
}

<h2>Alumnos</h2>

<div class="row">
    <div class="col-md-12">
        <h5>Seleccione un Alumno para editarlo o + para agregar...</h5>
        <hr />
    </div>
</div>

<div style="float:right;">
    @Html.ActionLink("+", "Form", "Alumno", htmlAttributes: new { @class = "btn btn-success" })
</div>
<br />

<table class="table table-bordered table-responsive">
    <thead>
        <tr>
            <td>Editar</td>

            <td class="visually-hidden">IdAlumno</td>
            <td>Nombre</td>
            <td>Numero de Boleta</td>
            <td>Usuario</td>
            <td class="visually-hidden">Password</td>
            <td>Email</td>
            <td>Telefono</td>

            <td>Eliminar</td>
        </tr>
    </thead>
    <tbody>
        @foreach (ML.Alumno alumno in Model.Alumnos)
        {
            <tr>
                <td><a class="btn btn-warning" href="@Url.Action("Form", "Alumno", new {IdAlumno = alumno.IdAlumno})"><i class="fas fa-pencil-alt"></i></a></td>
                <td class="visually-hidden">@alumno.IdAlumno</td>
                <td>@alumno.Nombre</td>
                <td>@alumno.NombreBoleta</td>
                <td>@alumno.UserName</td>
                <td class="visually-hidden">@alumno.Password</td>
                <td>@alumno.Email</td>
                <td>@alumno.Telefono</td>

                <td><a class="btn btn-danger" href="@Url.Action("Delete", "Alumno", new {IdAlumno = alumno.IdAlumno })" onclick="return confirm('Estás seguro que deseas eliminar este registro?');"><i class="fas fa-trash"></i></a></td>
            </tr>
        }
    </tbody>
</table>

MVCBoletas/Views/Alumno/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAll", "Alumno", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#modalValidacion').modal('show');
    });
</script>