MVCBoletas/Controllers/MateriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;

namespace MVCBoletas.Controllers
{
    public class MateriaController : Controller
    {
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Materia materia = new ML.Materia();
            var result = BL.Materia.GetAll();

            if (result.Correct)
            {
                materia.Materias = result.Objects;
            }
            return View(materia);
        }

        [HttpGet]
        public ActionResult Form(int? IdMateria)
        {
            ML.Materia materia = new ML.Materia();

            if (IdMateria != null)
            {
                var result = BL.Materia.GetById(IdMateria.Value);
                if (result.Correct)
                {
                    materia = (ML.Materia)result.Object;
                }
            }

            return View(materia);
        }

        [HttpPost]
        public ActionResult Form(ML.Materia materia)
        {
            try
            {
                if (materia.IdMateria == 0)
                {
                    var result = BL.Materia.Add(materia);

                    if (result.Correct)
                    {
                        ViewBag.Mensaje = "Registro exitoso";
                        return PartialView("Modal");
                    }
                    else
                    {
                        ViewBag.Mensaje = "Ocurrió un problema al agregar el registro: " + result.ErrorMessage;
                        return PartialView("Modal");
                    }
                }
                else
                {
                    var result = BL.Materia.Update(materia);

                    if (result.Correct)
                    {
                        ViewBag.Mensaje = "Actualización exitosa";
                        return PartialView("Modal");
                    }
                    else
                    {
                        ViewBag.Mensaje = "Ocurrió un problema al actualizar el registro: " + result.ErrorMessage;
                        return PartialView("Modal");
                    }
                }
            }
            catch (Exception ex)
            {
                // Loguea o maneja el error según tus necesidades
                ViewBag.Mensaje = "Ocurrió un problema: " + ex.Message;
                return PartialView("Modal");
            }
        }

        [HttpGet]
        public ActionResult Delete(int idMateria)
        {
            var result = BL.Materia.Delete(idMateria);

            if (result.Correct)
            {
                ViewBag.Mensaje = "Registro eliminado exitosamente";
                return PartialView("Modal");
            }
            else
            {
                ViewBag.Mensaje = "Ocurrió un problema al eliminar el registro: " + result.ErrorMessage;
                return PartialView("Modal");
            }
        }
    }
}

MVCBoletas/Views/Materia/Form.cshtml
@model ML.Materia


@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Formulario para agregar una Materia</h2>
<div class="row">
    <div class="container">
        <div class="col-md-12">
            <h2>Libros</h2>
            <h5>Ingrese los datos de la Materia:</h5>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @* Crea un salto de línea *@
            <hr />
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Materia", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-group">
                    @Html.HiddenFor(model => model.IdMateria)
                </div>

                <div class="form-group col-md-4 col-12 col-sm-6">
                    @Html.LabelFor(model => model.Nombre)
                    @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre" })
                    @Html.ValidationMessageFor(model => model.Nombre)
                </div>

                <div class="form-group col-md-4 col-12 col-sm-6">
                    @Html.LabelFor(model => model.Descripcion)
                    @Html.TextBoxFor(model => model.Descripcion, new { @class = "form-control", @id = "txtDescripcion" })
                    @Html.ValidationMessageFor(model => model.Descripcion)
                </div>


                <div class="col">
                    <div class="col-md-3">
                        <input type="submit" value="Guardar" class="btn btn-success" />
                        @Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })
                    </div>
                </div>
            }
        </div>
    </div>
</div>

MVCBoletas/Views/Materia/GetAll.cshtml
@model ML.Materia
@{
    ViewBag.Title = "GetAll";
}

<h2>Materias</h2>



<div class="row">
    <div class="col-md-12">
        <h5>Seleccione una Materia para editarla o + para agregar...</h5>
        <hr />
    </div>
</div>

<div style="float:right;">
    @Html.ActionLink("+", "Form", "Materia", htmlAttributes: new { @class = "btn btn-success" })
</div>
<br />

<table class="table table-bordered table-responsive">
    <thead>
        <tr>
            <td>Editar</td>
            <td class="visually-hidden">IdMateria</td>
            <td>Nombre</td>
            <td>Descripcion</td>

            <td>Eliminar</td>
        </tr>
    </thead>
    <tbody>
        @foreach (ML.Materia materia in Model.Materias)
        {
            <tr>
                <td><a class="btn btn-warning" href="@Url.Action("Form", "Materia", new {IdMateria = materia.IdMateria})"><i class="fas fa-pencil-alt"></i></a></td>

                <td class="visually-hidden">@materia.IdMateria</td>
                <td>@materia.Nombre</td>
                <td>@materia.Descripcion</td>

                <td><a class="btn btn-danger" href="@Url.Action("Delete", "Materia", new {IdMateria = materia.IdMateria })" onclick="return confirm('Estás seguro que deseas eliminar este registro?');"><i class="fas fa-trash"></i></a></td>
            </tr>
        }
    </tbody>
</table>

MVCBoletas/Views/Materia/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#modalValidacion').modal('show');
    });
</script>