MVCBoletas/Controllers/ProfesorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCBoletas.Controllers
{
    public class ProfesorController : Controller
    {
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Profesor profesor = new ML.Profesor();
            var result = BL.Profesor.GetAll();

            if (result.Correct)
            {
                profesor.Profesores = result.Objects;
            }

            return View(profesor);
        }

        [HttpGet]
        public ActionResult Form(int? IdProfesor)
        {
            ML.Profesor profesor = new ML.Profesor();

            if (IdProfesor != null)
            {
                var result = BL.Profesor.GetById(IdProfesor.Value);
                if (result.Correct)
                {
                    profesor = (ML.Profesor)result.Object;
                }
            }

            return View(profesor);
        }

        [HttpPost]
        public ActionResult Form(ML.Profesor profesor)
        {
            try
            {
                if (profesor.IdProfesor == 0)
                {
                    var result = BL.Profesor.Add(profesor);

                    if (result.Correct)
                    {
                        ViewBag.Mensaje = "Registro exitoso";
                        return PartialView("Modal");
                    }
                    else
                    {
                        ViewBag.Mensaje = "Ocurrió un problema al agregar el registro: " + result.ErrorMessage;
                        return PartialView("Modal");
                    }
                }
                else
                {
                    var result = BL.Profesor.Update(profesor);

                    if (result.Correct)
                    {
                        ViewBag.Mensaje = "Actualización exitosa";
                        return PartialView("Modal");
                    }
                    else
                    {
                        ViewBag.Mensaje = "Ocurrió un problema al actualizar el registro: " + result.ErrorMessage;
                        return PartialView("Modal");
                    }
                }
            }
            catch (Exception ex)
            {
                // Loguea o maneja el error según tus necesidades
                ViewBag.Mensaje = "Ocurrió un problema: " + ex.Message;
                return PartialView("Modal");
            }
        }

        [HttpGet]
        public ActionResult Delete(int idProfesor)
        {
            var result = BL.Profesor.Delete(idProfesor);

            if (result.Correct)
            {
                ViewBag.Mensaje = "Registro eliminado exitosamente";
                return PartialView("Modal");
            }
            else
            {
                ViewBag.Mensaje = "Ocurrió un problema al eliminar el registro: " + result.ErrorMessage;
                return PartialView("Modal");
            }
        }
    }
}

MVCBoletas/Views/Profesor/Form.cshtml
@model ML.Profesor

@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Formulario para agregar un nuevo Profesor</h2>
<div class="row">
    <div class="container">
        <div class="col-md-12">
            <h2>Profesores</h2>
            <h5>Ingrese los datos:</h5>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @* Crea un salto de línea *@
            <hr />
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Profesor", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-group">
                    @Html.HiddenFor(model => model.IdProfesor)
                </div>

                <div class="form-group col-md-4 col-12 col-sm-6">
                    @Html.LabelFor(model => model.Nombre)
                    @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre" })
                    @Html.ValidationMessageFor(model => model.Nombre)
                </div>

                <div class="form-group col-md-4 col-12 col-sm-6">
                    @Html.LabelFor(model => model.Email)
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @id = "txtEmail" })
                    @Html.ValidationMessageFor(model => model.Email)
                </div>


                <div class="form-group col-md-4 col-12 col-sm-6">
                    @Html.LabelFor(model => model.Usuario)
                    @Html.TextBoxFor(model => model.Usuario, new { @class = "form-control", @id = "txtUsuario" })
                    @Html.ValidationMessageFor(model => model.Usuario)
                </div>

                <div class="form-group col-md-4 col-12 col-sm-6">
                    @Html.LabelFor(model => model.Password)
                    @Html.TextBoxFor(model => model.Password, new { @class = "form-control", @id = "txtPassword" })
                    @Html.ValidationMessageFor(model => model.Password)
                </div>

                <div class="form-group col-md-4 col-12 col-sm-6">
                    @Html.LabelFor(model => model.Telefono)
                    @Html.TextBoxFor(model => model.Telefono, new { @class = "form-control", @id = "txtTelefono" })
                    @Html.ValidationMessageFor(model => model.Telefono)
                </div>

                

                <div class="col">
                    <div class="col-md-3">
                        <input type="submit" value="Guardar" class="btn btn-success" />
                        @Html.ActionLink("Regresar", "GetAll", "Profesor", htmlAttributes: new { @class = "btn btn-danger" })
                    </div>
                </div>
            }
        </div>
    </div>
</div>

MVCBoletas/Views/Profesor/GetAll.cshtml
@model ML.Profesor
@{
    ViewBag.Title = "GetAll";
}


<h2>Profesores</h2>

<div class="row">
    <div class="col-md-12">
        <h5>Seleccione un Profesor para editarlo o + para agregar...</h5>
        <hr />
    </div>
</div>

<div style="float:right;">
    @Html.ActionLink("+", "Form", "Profesor", htmlAttributes: new { @class = "btn btn-success" })
</div>
<br />

<table class="table table-bordered table-responsive">
    <thead>
        <tr>
            <td>Editar</td>

            <td class="visually-hidden">IdProfesor</td>
            <td>Nombre</td>
            <td>Email</td>
            <td>Usuario</td>
            <td>Password</td>
            <td>Telefono</td>

            <td>Eliminar</td>
        </tr>
    </thead>
    <tbody>
        @foreach (ML.Profesor profesor in Model.Profesores)
        {
            <tr>
                <td><a class="btn btn-warning" href="@Url.Action("Form", "Profesor", new {IdProfesor = profesor.IdProfesor})"><i class="fas fa-pencil-alt"></i></a></td>

                <td class="visually-hidden">@profesor.IdProfesor</td>
                <td>@profesor.Nombre</td>
                <td>@profesor.Email</td>
                <td>@profesor.Usuario</td>
                <td>@profesor.Password</td>
                <td>@profesor.Telefono</td>

                <td><a class="btn btn-danger" href="@Url.Action("Delete", "Profesor", new {IdProfesor = profesor.IdProfesor })" onclick="return confirm('Estás seguro que deseas eliminar este registro?');"><i class="fas fa-trash"></i></a></td>
            </tr>
        }
    </tbody>
</table>

MVCBoletas/Views/Profesor/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAll", "Profesor", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#modalValidacion').modal('show');
    });
</script>